services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui
    ports:
      - "9090:8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:29092
    depends_on:
      - kafka1
    networks:
      - kafka-net
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - kafka-net
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:29092,OUTSIDE://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 77
      KAFKA_LOG_RETENTION_MS: 30000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      KAFKA_LOG_RETENTION_BYTES: 78
#      KAFKA_LOG_ROLL_MS: 5000
      KAFKA_LOG_SEGMENT_BYTES: 77
#      KAFKA_NUM_PARTITIONS: 3 # default partitions per topic when topic is auto created
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
    networks:
      - kafka-net
    depends_on:
      - zookeeper
networks:
  kafka-net:
    driver: bridge